apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-microservice
  labels:
    app: nodejs-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-microservice
  template:
    metadata:
      labels:
        app: nodejs-microservice
    spec:
      containers:
        - name: nodejs-microservice
          image: capstoneacrmicrodeploy.azurecr.io/nodejs-microservice:latest
          ports:
            - containerPort: 8080
