apiVersion: v1
kind: Service
metadata:
  name: nodejs-microservice-service
spec:
  selector:
    app: nodejs-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
