apiVersion: v1
kind: Service
metadata:
  name: nodejs-microservice-service
spec:
  selector:
    app: nodejs-microservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
